manifests/plugin/gutterball.pp
manifests/plugin/gutterball/config.pp
templates/plugin/gutterball/gutterball.yaml.erb

depends on https://github.com/Katello/puppet-gutterball/pull/6

Ref #9134 - gb plugin sets configs for foreman-gutterball

---

manifests/init.pp
spec/classes/katello_spec.rb

Add parameters for configuring the client, needed for the changes that happened in https://github.com/Katello/puppet-qpid/pull/12

refs #9060 - configure qpid::client with params

---

metadata.json

Incompatible changes were made - e.g., param removal of mongod_path.

Bump to 2.0.0

---

manifests/init.pp

The ca_key and ca_cert options are used by Pulp when creating and
signing consumer certs. Not only do we not use this ability of Pulp
but these options are being deprecated by Pulp.

Don't pass ca cert/key to Pulp

---

manifests/init.pp
templates/etc/httpd/conf.d/05-foreman-ssl.d/katello.conf.erb

Requires https://github.com/Katello/puppet-certs/pull/70

Fixes #13189 - allows for certificate authentication of capsules

---

manifests/init.pp

This adds support for truststore password for candlepin, as pushed in PR#32.
I will also open a PR for puppet-certs to add the corresponding parameter

add a truststore_password parameter for candlepin

---

spec/classes/katello_config_spec.rb
templates/katello.yaml.erb

Updating server post sync url to fqdn since it needs to match the cn in
the katello cert and not (localhost)

Fixes #13503 - Updating post sync url

---

manifests/config.pp
manifests/config/pulp_client.pp
manifests/init.pp

The previous commit (https://github.com/Katello/puppet-katello/commit/4ecc339d16b88f1a450f075fc14e0c0a103a3e4a) added two cycles to the puppet dep graph, causing `katello-installer` to fail.
The offending line was:
```
require        => [Exec['foreman-rake-db:seed'], Class['::certs::pulp_client']],
```
Note that each of these `require`s individually will cause a cycle. The cycle for just `foreman-rake-db:seed` is http://i.imgur.com/eA8rWc6.png and the cycle for `::certs::pulp_client` is http://i.imgur.com/EgeI2X2.png.
Removal of these lines makes `katello-installer` succeed.

Refs #13658 - remove cycle from puppet graph

---

manifests/install.pp
spec/classes/katello_install_spec.rb

Enabling ostree functionality requires restart of httpd and foreman-tasks
This code provides that functionality

Fixes #14324 - Restarts foreman-tasks and httpd on ostree enable

---

manifests/config.pp
manifests/init.pp
manifests/params.pp

Previously, there was no default location for repository exports. This meant
that users had to "leave" Katello and hop into the command line prior to
creating their first repo export.
This commit creates a `/var/lib/pulp/katello-export` directory as part of the
install. Users may optionally point this elsewhere via installer parameter if
needed.
The `/var/lib/pulp/katello-export` directory was chosen since users already
expect that `/var/lib/pulp` and its child dirs may have large disk space
requirements.

Refs #14698 - create default directory for repo exports

---

manifests/init.pp
manifests/params.pp

Companion PR's:
Test box:
```
mongoauth:
box: centos7-katello-nightly
options: --module-prs katello/126,pulp/146,capsule/84
```

fixes #15058 - enable mongo auth

---

manifests/params.pp

Tomcat not used and 'file_exists' is master side only. This does not work as expected except when using the masterless installer.

Remove 'tomcat' param

---

spec/classes/katello_config_spec.rb
templates/katello.yaml.erb

This is necessary because we have various operations in Katello that
are synchronus, especially around our interaction with candlepin and
manifest import that we will often time-out during operation.
We need to keep this timeout value high until the API calls we rely on
are implemented in an async manner.

Fixes #15170 - Moving timeout to a large enough value

---

manifests/params.pp

Since 069214ae72419faf122ec465265cec969e9b4924 this parameter is unused.

Remove unused $rhsm_url variable

---

manifests/qpid.pp

Messages are not being received from candlepin due to exec
blocks not being executed sequentially. The 2nd exec{} is dependent
on the 1st exec{} being completed successfully.

Fixes #15727 - Not receiving candlepin messages

---

templates/etc/httpd/conf.d/05-foreman-ssl.d/katello.conf.erb
templates/etc/httpd/conf.d/05-foreman.d/katello.conf.erb

Previously, this vhost def was disabling passenger even if passenger was not
installed, causing errors.

Wrap `PassengerEnabled` in module check

---

manifests/init.pp

This is a little used feature and extra wsgi
processes use up more open file handles

Fixes #15841 - limit pulp puppet wsgi procs

---

manifests/init.pp
manifests/params.pp
manifests/qpid.pp
spec/classes/katello_config_spec.rb

Required PR's
Test with:
`./setup.rb --module-prs katello/79,capsule/55,gutterball/17,certs/65`
Existing katello needs upgrade and certs update:
```
foreman-installer --scenario katello --certs-update-all --upgrade
```

refs #11737 - connect to localhost for qpid

---

manifests/init.pp
manifests/params.pp
templates/etc/httpd/conf.d/05-foreman-ssl.d/katello.conf.erb

https://github.com/theforeman/puppet-foreman/commit/0a6966ce22111b1ce592b5e215a948b3734680e7 introduced these parameters in puppet-foreman so these are duplicate.
It should be noted that puppet-foreman has a very different default (100) from what's removed here (10000). It should also be added in a migration in katello-installer if we decide to do this.

Remove keepalive settings

---

manifests/init.pp

Previously puppet-capsule enabled crane on both capsules and crane,
but this has moved into the pulp config which is currently separate
Needs https://github.com/Katello/puppet-pulp/pull/170

Enable crane in Katello too

---

spec/classes/katello_config_spec.rb
spec/classes/katello_install_spec.rb
spec/classes/katello_spec.rb

By using on_supported_os we can benefit from ONLY_OS thus reducing our test runtime. The use of verify_exact_contents makes it slightly easier to read.

Optimize tests

---

manifests/init.pp
manifests/params.pp

!!Merge once Pulp >= 2.11 is added to Katello!!
This feature requires Pulp >= 2.11. It allows setting of maximum number of tasks after which the celery worker gets recycled and releases its memory to the system.
It requies https://github.com/Katello/puppet-pulp/pull/173 to be merged.

Fixes #17298 - Add max tasks per Pulp worker

---

manifests/init.pp

pulp should have katello enabled so that the package `pulp-katello` is installed. On a all-in-one install this happens because the katello package depends on pulp-katello.
https://github.com/Katello/katello-packaging/blob/master/katello/katello.spec#L40

pulp: enable katello

---

manifests/init.pp

This commits adds code to refresh services when certs change.
Previously, this has been done in puppet-certs module.

refresh services when certs change

---

manifests/qpid.pp

@ekohl needed Katello changes for your key specification

Specify qpid SSL key to qpid commands

---

manifests/init.pp

I thought I had pushed this little update with the previous PRs. Fixes the last of cycles:
```
(Exec[cpinit] => Class[Candlepin::Service] => Class[Candlepin] => Class[Candlepin] => Class[Qpid] => Class[Qpid::Service] => Service[qpidd] => Exec[qpid-config ensure exchange event] => Qpid::Config_cmd[ensure exchange event] => Qpid::Config::Exchange[event] => Class[Candlepin::Qpid] => Class[Candlepin::Service] => Exec[cpinit])
```

Fix dependency cycle from Candlepin exchange migration

---

files/katello-apache-ssl.conf
files/pulp-apache-ssl.conf
files/pulp-apache.conf
manifests/config.pp

This patch drops support for Apache 2.2, but we only support EL7 which
ships 2.4.
It is untested, but I need this to easily test it in a pipeline run.

Split apache fragments

---

manifests/init.pp

as it should be handled by foreman_proxy_content, that pulls
in crane.

Remove crane_data_dir

---

manifests/init.pp
manifests/params.pp

Exposing Candlpin DB parameters via katello module allows users to
customize the DB setup using installer parameters.
Current default Candlepin DB setup remains unaffected. Using external
Postgress with prepared DB is possible.
I've tested the default Katello install and also fresh installation with remote DB using:
```
foreman-installer --scenario katello --foreman-admin-password changeme --foreman-db-host X.X.X.X --foreman-db-password foreman --foreman-db-database foreman --katello-candlepin-db-host X.X.X.X - -katello-candlepin-db-name candlepin --katello-candlepin-db-password candlepin
``` 
The remote DB use-case assumes 
- the DB server allows connection from the Katello server 
- has one database for Foreman and one for Candlepin
- postgress users owning the databases can auth in …

Fixes #19667 - expose Candlepin DB setup

---

manifests/params.pp

Downstream this change was made for performance reasons, reference in the following BZ:
https://bugzilla.redhat.com/show_bug.cgi?id=1388631

Fixes #20518 - set pulp tasks to 2

---

manifests/install.pp
spec/classes/katello_install_spec.rb

We need to run ```/usr/sbin/foreman-rake apipie:cache:index ``` after installing ostree. So added that option in the installer and closing https://github.com/Katello/katello-packaging/pull/483

fixes #20353 - Runs apipie cache after ostree

---

manifests/init.pp
manifests/params.pp

This parameter does not exist EPEL's qpid 1.36 causing qpidd refusing to start.

Remove $qpid_session_unacked

---

manifests/candlepin.pp

This was previously in puppet-certs as /usr/share/tomcat/conf/keystore
but it doesn't belong there. Because /usr/share/tomcat/conf is a symlink
to /etc/tomcat we can safely manage it here as well without duplicating
resources.

Ensure the candlepin keystore symlink

---

manifests/application.pp
manifests/candlepin.pp
manifests/qpid_client.pp
spec/classes/katello_application_spec.rb
spec/classes/katello_candlepin_spec.rb

The `qpid_ssl_cert` and `qpid_ssl_key` parameters for `candlepin` are just to [set up an exchange](https://github.com/Katello/puppet-candlepin/blob/bdcfccd827e2f8f5477e37a1f20923641fb4439a/manifests/qpid.pp#L7-L10).
This can be done with candlepin's qpid certificates and removed the dependency for qpid's certificates.

candlepin: use own certs for qpid

---

manifests/pulp.pp
spec/classes/katello_pulp_spec.rb

This PR removes the dependency for candlepin from pulp.
This has never worked in the past. We need to properly design this and should implement a working solution.
https://github.com/Katello/puppet-pulp/blob/3bf701bacc8d98cdb49ac37d301322fbce941163/manifests/config.pp#L118-L124
The `refreshonly => true` requies the exec to be notified before it runs. It's never notified.

pulp: remove candlepin consumers crl

---

manifests/init.pp
manifests/params.pp
manifests/qpid.pp
spec/classes/katello_qpid_spec.rb

This PR allows configuring the hostname that is used to connect to `qpidd` while setting up queues etc. This is necessary when a developer sets `interface` to something else than `lo`.

qpidd: hostname for config cmds

---

manifests/init.pp
manifests/params.pp
manifests/pulp.pp
spec/classes/katello_pulp_spec.rb

This patch exposes most of the Pulp DB configuration and visible from installer.
The params are listed as advanced and not pollute installer --help.
I was able to install Katello with remote mongo with:
```
foreman-installer \
--scenario katello \
--katello-pulp-db-username=pulp_user \
--katello-pulp-db-password=pulp \
--katello-pulp-db-seeds="192.168.121.43:27017" \
--katello-pulp-db-name="pulp_database" \
--foreman-admin-password=changeme
```

Fixes #22907 - expose Pulp DB configuration params

---

manifests/pulp.pp
templates/pulp-apache-ssl.conf.erb
templates/pulp-apache.conf.erb

Hi,
These changes make the Apache directory options for /pub configurable via custom-hiera.yaml.
This is helpful when you need to disable directory listing for security scanner compliance.
By default nothing is changed, but if directory listing of /pub (both HTTP and HTTPS) were desired, adding the following line to `/etc/foreman-installer/custom-hiera.yaml` would prevent autoindex:
~~~
katello::pulp::pub_dir_options: "+FollowSymLinks"
~~~
Thank you in advance, and special thanks to @beav for all the help!

Fixes #23624 - make Apache directory options for /pub configurable

---

manifests/qpid.pp
manifests/qpid_client.pp

While it's also available at the certs top scope, it's not the most accurate place. This also points out we really only use the certs::qpid and certs is more an internal detail. We should probably look at only including certs::qpid which is probably enough due to the inhertince but that's for later.

Refer to the correct $nss_db_ variable

---

manifests/application.pp
manifests/params.pp
spec/classes/katello_application_spec.rb
templates/katello.yaml.erb

Relies on https://github.com/Katello/katello/pull/7249
https://github.com/theforeman/puppet-katello_devel/pull/168
https://github.com/theforeman/puppet-katello/pull/243
https://github.com/Katello/katello/pull/7543

fixes #24070 - add registry to katello.yaml

---

metadata.json

puppetlabs/stdlib 4.6.0 is a non-existent version. This change was introduced in https://github.com/theforeman/puppet-katello/commit/898eae48d45b0a3785c1dbabce1d35ca3f7c02be and subsequently the rest of the commit removed in https://github.com/theforeman/puppet-katello/commit/5de2e01795aac52e84cd88dc5d57b0841de8657e. This change is to roll back the minimum required version of stdlib to 4.25.1. I have ran a test against that here: https://travis-ci.org/SeanHood/puppet-katello/jobs/444994576. `.fixtures.yml` needed to be changed to allow for this, hence missing from this commit.
The reason behind this change is that a handful of modules still have a requirement on < 5.0.0. This module doesn't use any of the newly introduced functions in that release.

Allow puppetlabs/stdlib => 4.25.1

---

manifests/params.pp
spec/classes/katello_pulp_spec.rb

https://projects.theforeman.org/issues/25511

Fixes #25511 - Disable max tasks by default to prevent memory issues.

---

manifests/params.pp
spec/classes/katello_spec.rb

f614db22fdb78f67b2e778f1729512683de4a251 removed the use of $rubygem_katello_ostree variable, but not its definition.
We also don't want to hard fail because we sometimes want to compile on other distros. The most common use case is CI testing our installer by running it with --help. Since that happens on Travis (which is Ubuntu) it hard fails.

Simplify package name handling

---

manifests/params.pp
metadata.json

These don't generate deprecation warnings.

Use namespaced extlib functions

---

manifests/pulp.pp

Pulp's server config has a setting for the server name. We should match this to the name we use on the vhost. Currently that's tied to the Foreman vhost so we can make that explicit here.

Refs #26103 - Set the pulp server_name

---

manifests/init.pp
spec/classes/katello_spec.rb

this is required for Candlepin 2.5.10, see [1] for details
[1] https://bugzilla.redhat.com/show_bug.cgi?id=1570534

Fixes #25966 - order all candlepin actions after qpid

---

files/qpid_acls.acl
manifests/qpid.pp
metadata.json

(cherry picked from commit fb3804643925b5177d7443f112641b29c5d74155)
@ekohl here's the pick for 3.10.1
- puppet-qpid: https://github.com/theforeman/puppet-qpid/pull/123
- I think puppet-foreman_proxy_content needs a 7.3-stable branch for me to pick on to, but I have a branch prepared locally

[CP] Refs #26571 - Add Qpid ACL file

---

.fixtures.yml

Pulp started to use the selboolean type which requires selinux_core to be added to the fixtures on Puppet 6.

Add selinux_core to the test fixtures

---

files/katello-apache-ssl.conf

This matches what theforeman-foreman sets and avoids SSL renegotiations.

Fixes #27656 - Set SSLVerifyDepth to 3

---

manifests/application.pp
manifests/params.pp
manifests/qpid.pp
spec/classes/katello_application_spec.rb
spec/classes/katello_qpid_spec.rb

76a9876 Drop katello entitlements queue cleanup
ba8aae68386aa352149822fd9937decdf2677232 started to drop the entitlements queue bound to *.*. Sufficient time has passed to assume all these instances have been cleaned up and can be removed.
c55aa32 Remove bundler.d/katello.rb
In 6476f28f50e8256615403b07ce447d3315d70d85 this file was changed to set the permissions to match packaging. Sufficient time has passed to assume all setups have been upgraded so this cleanup can be removed.

Drop old workarounds

---

manifests/application.pp
manifests/candlepin.pp
manifests/init.pp
manifests/params.pp
manifests/pulp.pp
manifests/qpid.pp
manifests/repo.pp
spec/classes/katello_application_spec.rb
spec/classes/katello_candlepin_spec.rb
spec/classes/katello_pulp_spec.rb
spec/classes/katello_repo_spec.rb
spec/classes/katello_spec.rb

While it's not possible to collect classes, it is possible to collect anchors. This allows including it anywhere and the right dependency will be set.
This is used to simplify the main class. As an example, the katello::repo is extracted. Ideally all classes become standalone so they can be exposed to the user in the installer. It also makes it easy to do split deployments.

Implement automatic dependency chaining

---

manifests/application.pp
manifests/candlepin.pp
manifests/globals.pp
manifests/init.pp
manifests/params.pp
manifests/pulp.pp
manifests/qpid.pp
manifests/qpid_client.pp
spec/classes/application_spec.rb
spec/classes/candlepin_spec.rb
spec/classes/init_spec.rb
spec/classes/pulp_spec.rb
spec/classes/qpid_spec.rb

Every class that provides an aspect of the deployment is now standalone. This means:
* candlepin
* pulp
* qpid
* application
They can just be included and work by themselves. All class parameters are tunables that users will commonly modify.
There's also shared parameters which are common among the standalone classes. These are meant to be changed via katello::params. Either via Hiera or by including them in a profile class before the instance classes themselves.
The katello::globals class has globals that a user via the installer might want to change. The katello::params class is not intended to be exposed via the installer.
Currently a draft because I want to do testing with rewriting the changes in the installer. Having this in a PR makes that easier.
Includes:
* …

Redesign classes to allow split deployments

---

manifests/application.pp
manifests/init.pp
spec/classes/application_spec.rb

We need to support Strings as well because we might need the protocol for the proxy.
E.g. this Katello seed will fail if the proxy is specified without a protocol: https://github.com/Katello/katello/blob/master/db/seeds.d/115-http_proxy.rb#L3
The datatype was changed in https://github.com/theforeman/puppet-katello/pull/308

Use Stdlib::Httpurl datatype to support setting a proxy protocol

---

manifests/qpid.pp
manifests/qpid_client.pp
metadata.json

Rather than hardcoding it, the certs class that actually creates these should be responsible for naming it.
Draft because it depends on https://github.com/theforeman/puppet-certs/pull/265

Use the nss cert name from certs::qpid

---

manifests/pulp.pp
metadata.json
spec/classes/pulp_spec.rb

certs 7.0.0 started to create qpid files owned by the pulp group. This group is created by pulp-server which is in pulp::install. This more specific chaining avoids dependency cycles.
This is an alternative to https://github.com/theforeman/puppet-certs/pull/270. Related to https://github.com/theforeman/puppet-certs/pull/272.

Compatibility with katello/certs 7.x

---

manifests/application.pp
manifests/init.pp
manifests/pulp.pp
spec/classes/application_spec.rb
spec/classes/pulp_spec.rb

By using only the Apache config, it's possible to use the Apache config without Foreman installed.
Depends on https://github.com/theforeman/puppet-foreman/pull/800

Refs #29039 - Use foreman's Apache config standalone

---

.fixtures.yml
spec/classes/application_spec.rb

* a57f571 Remove coupled expectation
The `Exec[restart_foreman]` resource is part of `Foreman::Service` when Passenger is used. Since the default flipped, this is no longer the case. Since it's an implementation detail, we no longer need to test for this.
* a48e2d8 Add transition to fixtures
puppet-pulp has started to depend on this.

Fix the tests

---

manifests/application.pp
manifests/init.pp
spec/classes/application_spec.rb
templates/katello.yaml.erb

Needs https://github.com/Katello/katello/pull/8552 to be merged first

Fixes #28906 - Remove cdn_ssl_version from module

---

manifests/params.pp

The datatype has to be `HTTPSUrl` instead of `Httpsurl` to not break the foreman-installer if using the `params.pp` directly:
```
[root@foreman4xng ~]# foreman-installer --scenario custom --noop --verbose
[FATAL 2020-04-02T08:01:02 fatal] Unable to continue because of: unknown data type Stdlib::Httpsurl
```
I'm not really sure why this works when just including the class without specifying the parameters explicitly (like in https://github.com/theforeman/puppet-katello/blob/master/manifests/init.pp#L159-163)
see https://github.com/puppetlabs/puppetlabs-stdlib#stdlibhttpsurl

Fix Stdlib::HTTPSUrl type name

---

manifests/application.pp
manifests/globals.pp
manifests/params.pp
spec/classes/application_spec.rb

Adds the postgresql-evr package to katello.

Add postgresql-evr extension to katello

---

manifests/pulp.pp
spec/classes/pulp_spec.rb

Follow up to #312
This PR enables Pulp to exist as a standalone system and therefore enables split deployments.
The default behaviour does not change in any way. It it explicitly required to set a least manage_httpd to true.
Note: The original PR is #312. Because the source branch was missing, I needed to open a new PR with an existing branch I can push to.

Support manage_httpd to allow Pulp in a standalone setup (followup)

---

manifests/application.pp
manifests/globals.pp
manifests/params.pp
spec/classes/application_spec.rb

This reverts commit 6b0c9b4c7374cc6c577642d8fd6c9277b9bcd46a.
Initially this was merged because the support was [needed in Katello](https://github.com/Katello/katello/commit/514770541975012ea85a5780fd67c237cb535e2d). Later this PR was [reverted](https://github.com/Katello/katello/commit/a569779c9d8f623de1fed00c2d8ca0a89bf483d1).

Revert "Add postgresql-debversion extension to katello"

---

Gemfile

This allows installing fewer gems for specific tests.

Assign more groups in Gemfile

---

metadata.json

There have been breakin changes so it's good to increase the major version. A stable version will be released and master shouldn't be an older version than what's released.

Bump major version to 17

---

templates/pulp-apache.conf.erb

Follow on for: a0917838fabc8241e3e5e7f678378a2d45cbea54

Drop inclusion of pulp-vhosts80 with no managed content types

---

.fixtures.yml
metadata.json

aa27779c4bf46442d5a5543c54e593798ce580af removed Pulp deployments. This also drops the dependencies on the (now) unused modules.

Refs #30360: Remove unused dependencies

---

manifests/qpid.pp
metadata.json
spec/acceptance/qpid_spec.rb
spec/setup_acceptance_node.pp

This is an alternative to https://github.com/theforeman/puppet-katello/pull/388. The last commit should not be added, but is there to allow this to pass CI.

Refs #31878 - Allow external mechanism for qpid SASL

---

metadata.json

In ce98aab5a87dd542eaf649622f0aa7df6207f2d5 the qpid dependency was set to >= 6.2.0 but 6.2.0 was already released. It was just that master still had 6.1.0 which confused me. This corrects the matter and allows the newer version to be used.
Requires https://github.com/theforeman/puppet-qpid/pull/146
Fixes: ce98aab5a87dd542eaf649622f0aa7df6207f2d5

Refs #31878 - Correct qpid dependency

---

manifests/application.pp
manifests/init.pp
metadata.json
spec/classes/application_spec.rb

This uses the new foreman::dynflow::pool defined type which allows users to easily add additional workers or scale them back.
Currently a draft since it's pointing to my branch in the fixtures to allow testing. Blocked on https://github.com/theforeman/puppet-foreman/pull/843.

Refs #29817 - Implement a resizable hosts_queue pool

---

metadata.json

There is no ScientificLinux 8. The effort was folded into the CentOS project.

Remove Scientific 8 support from metadata.json

---

README.md

Update the supported platforms to include RHEL8 as well. Support for this was added with #335 but this change didn't update the README as well.
Closes #397

Update Limitations in README

---

manifests/globals.pp
manifests/init.pp
manifests/params.pp
spec/classes/application_spec.rb
types/hieraboolean.pp

This moves the content enable flags to the params class and away from
init.pp. This will allow a user to either set these via the globals
class or via hiera.

Refs #32369 - Move content enable flags to params

---

manifests/qpid.pp
spec/classes/qpid_spec.rb

Katello uses the Foreman client certificates to talk to Qpid when
katello-agent support is enabled, the same should be used when
setting up Qpid queues and exchanges and not the server certificates
that are intended to be used by Qpid itself.

Use Foreman client certificates to setup qpid queues

---

spec/classes/application_spec.rb
templates/katello.yaml.erb

Since Katello 4.2 this setting doesn't exist anymore.

Remove katello_applicability setting

---

manifests/application.pp
manifests/globals.pp
manifests/params.pp
spec/classes/application_spec.rb
templates/katello.yaml.erb

Since Katello 4.2 these are no longer needed and determined dynamically.

Fixes #33830 - Drop content type settings

---

CHANGELOG.md
metadata.json

Release 21.1.0

---

.fixtures.yml
manifests/candlepin.pp
metadata.json

This reverts commit bda1511b88b7954230a0e3bb1a2a71c5b6920e5e.
See https://github.com/theforeman/puppet-certs/pull/386
Candlepin cannot start when a encrypted key is generated using genpkey or on a FIPS enabled machine. Therefore, we should revert to handing Candlepin an unencrypted key.

Configure Candlepin with unencrypted CA key

---

manifests/application.pp
spec/classes/application_spec.rb

These settings were introduced with Pulp 2 and carried over to Pulp
3 before we introduced client authentication support in smart_proxy_pulp.
The support for using Foreman client certificates to talk to Pulp 3 was
introduced in Foreman 3.0. This is now safe to drop.

Fixes #35005: Drop setting Pulp client certificate settings

---

lib/puppet/functions/katello/build_dn.rb
manifests/application.pp
manifests/candlepin.pp
manifests/init.pp
spec/acceptance/candlepin_spec.rb
spec/acceptance/katello_spec.rb
spec/classes/candlepin_spec.rb
spec/classes/init_spec.rb
spec/functions/katello_build_dn_spec.rb

Moving the computation of the Artemis client DN into this class
instead of relying on the value provided directly by classes in
puppet-certs aims to solve two problems:
1) Testing at all levels of the value of the client DN
2) Adding a function to calculate the DN based on a set of values and
ignoring any empty values which do not end up in the actual certificate
Additionally this removes the layers of indirection `certs::candlepin::artemis_client_dn` which pointed `certs::foreman::client_dn` and moves the calculation closer to the input as this class serves to bring another of items together to properly configure Candlepin/Artemis/Tomcat.
This aims to solve a reported [BZ from Satellite](https://bugzilla.redhat.com/show_bug.cgi?id=1964037) where if a user customizes parts of the …

Calculate the client DN for Artemis, ignoring empty values

---

lib/puppet/functions/katello/build_dn.rb
spec/functions/katello_build_dn_spec.rb

There exists the possibility a parameter passed to build_dn could be an empty string which breaks the previous requirement on a string of length at least one, String[1]. Change to accept any length string but if the string happens to be empty, filter it out of the calculation.

Allow but filter out empty strings in build_dn

---

manifests/init.pp
manifests/params.pp
spec/classes/init_spec.rb

this is useful for downstream branding

allow overriding the name of the metapackage

---

manifests/repo.pp
spec/classes/application_spec.rb
spec/classes/repo_spec.rb

The version `latest` doesn't exist. This drops the default and adds stricter validation. Because other values this can be considered a bugfix, even though technically it's changing the API.
Fixes #472

Remove invalid default for $katello::repo::repo_version

---

manifests/repo.pp

We don't intend to use modularity on the initial release, so scope this to only EL8.

Only install dnf module on EL8

---

manifests/candlepin.pp
manifests/init.pp
spec/classes/init_spec.rb

For reference: https://github.com/theforeman/puppet-candlepin/pull/262#pullrequestreview-2085605414
This PR adds `facts_match_regex` parameter support to `katello::candlepin`. It enables filtering consumer facts via regex patterns, enhancing configuration flexibility and control.
- Introduced `facts_match_regex` parameter in `katello::candlepin`.
- Updated `katello` class to pass `facts_match_regex` to `katello::candlepin`.
- Added unit tests to validate parameter functionality.

Add facts_match_regex parameter in katello class

---

metadata.json

e057cf36147ece1fb9827e9122f98e9ab1ce0ba7 started using a parameter that was introduced in 16.1.0.
Fixes: e057cf36147e ("Add facts_match_regex paramter in katello class")

Correct minimum version of katello/candlepin

---

manifests/application.pp
manifests/globals.pp
manifests/params.pp
spec/classes/application_spec.rb
spec/setup_acceptance_node.pp

Ref: https://github.com/Katello/katello/pull/11087 which removes postgresql_evr from katello and adds the migration to create the type and trigger needed.
Goal of this PR is to uninstall postgresql_evr on existing setups and to stop installing it on new ones.

Fixes #37680 - Stop installing postgresql_evr extension

---

manifests/application.pp
spec/classes/application_spec.rb

Long term solution is to remove this configuration and rely on the application to use the Foreman settings (https://github.com/Katello/katello/pull/11327). This is needed to fill the gap in the short term.

Use Foreman CA certificate bundle instead of removed certs::ca_cert

---

metadata.json

https://forge.puppet.com/modules/puppetlabs/apache 13.0.0 was released, but our modules only allow "< 13"
Updating upper bound to "< 14" to fix this issue

Allow puppetlabs/apache 13.x
