.gitignore, .puppet-lint.rc, .travis.yml, CONTRIBUTING.md, Gemfile, Rakefile, manifests/init.pp, manifests/params.pp, manifests/plugin/gutterball.pp, metadata.json, spec/spec.opts, spec/spec_helper.rb
Adding support for Scientific Linux
=> Updates from modulesync

.fixtures.yml, manifests/init.pp, metadata.json
Goes with https://github.com/Katello/katello-installer/pull/267 and https://github.com/Katello/katello-packaging/pull/82
=> Fixes #10291 - removes elasticsearch

.fixtures.yml, manifests/init.pp, metadata.json
Updating https://github.com/Katello/puppet-katello/pull/109
=> fixes #13451 - enables squid management in pulp

manifests/init.pp
https://github.com/Katello/puppet-capsule/pull/105
=> Crane moved back to capsule for now

manifests/pulp.pp
As requested in:
https://github.com/Katello/katello/pull/6877#issuecomment-353515115
=> Enable pulp_deb for katello

manifests/application.pp
(cherry picked from commit c9242751287e34bb9afe0e60159bfe06f74d2802)
=> Fixes #24854 - Update rest_client param reference in application.pp

spec/classes/katello_application_spec.rb, spec/classes/katello_spec.rb
The candlepin class no longer runs cpinit so this test started to fail.
=> Correct the candlepin dependency checks

files/qpid_acls.acl, manifests/qpid.pp
Depends on https://github.com/theforeman/puppet-qpid/pull/120
=> Refs #26571 - Add Qpid ACL file

manifests/application.pp, manifests/init.pp, manifests/params.pp, spec/classes/katello_application_spec.rb, templates/katello.yaml.erb
as the application no longer uses it
=> Remove post_sync_url from config

manifests/application.pp, manifests/init.pp, spec/classes/application_spec.rb, templates/katello.yaml.erb
This change removes the cdn proxy and HTTP proxy configurations.
=> Fixes #28837 - removes cdn_proxy from config

manifests/application.pp, manifests/globals.pp, metadata.json, spec/classes/application_spec.rb
Since version 15.0.0 the define does everything this module needs in the correct order.
https://github.com/theforeman/puppet-foreman/pull/808 is related.
=> Use foreman::plugin to define the plugin

metadata.json
=> correct needed foreman dependency

manifests/application.pp, manifests/globals.pp, manifests/params.pp, spec/classes/application_spec.rb
educated copy of https://github.com/theforeman/puppet-katello/pull/332 for the `debversion`-extension
=> Add postgresql-debversion extension to katello

manifests/application.pp, manifests/qpid_client.pp, spec/classes/application_spec.rb, spec/classes/init_spec.rb, spec/classes/qpid_client_spec.rb
This reverts commit 990b7d2c78a31d271064e912760f8dc0fe0a6f2d.
=> Fixes #31693 - Restore katello::qpid_client

manifests/application.pp, manifests/params.pp, manifests/qpid.pp, spec/classes/application_spec.rb, spec/classes/qpid_spec.rb, templates/katello.yaml.erb, templates/qpid_acls.acl
Will test once green - just winging it
=> Fixes #31761 - create katello.agent qpid queue

manifests/params.pp, spec/classes/application_spec.rb
Supports https://github.com/Katello/katello/pull/9166
=> Refs #31880 - Switch to AMQP 1.0 SSL URL

manifests/application.pp, manifests/globals.pp, manifests/params.pp, manifests/qpid.pp, metadata.json, spec/acceptance/qpid_spec.rb, spec/classes/application_spec.rb, spec/classes/qpid_spec.rb, templates/katello.yaml.erb
=> Refs #32037: Add flag to enable katello_agent infrastructure and disable it by default

metadata.json
Needed to drop Puppet 5 -- https://github.com/theforeman/puppet-katello/pull/416
=> Bump version to 21.0.0

spec/acceptance/candlepin_spec.rb, spec/acceptance/hieradata/common.yaml, spec/acceptance/hieradata/os/RedHat/7.yaml, spec/acceptance/katello_spec.rb, spec/acceptance/qpid_spec.rb, spec/setup_acceptance_node.pp, spec/support/acceptance/purge.rb
Giving this a try to see if it can help find issues earlier and identify any problems with some cross module changes that are orchestrated here. This currently fails because nightly fails.
=> Add basic acceptance test for the whole module

CHANGELOG.md
Potential open PRs that are testing focused:
=> Release 21.0.0

manifests/application.pp, spec/acceptance/hieradata/common.yaml
This is part of the effort that was originally https://github.com/theforeman/foreman-installer/pull/754
=> Include apache::mod::setenvif

CHANGELOG.md, metadata.json
waiting on:
- https://github.com/theforeman/puppet-katello/pull/447
=> Release 21.5.0
